name: Deploy to Fly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install Fly CLI
      run: curl https://fly.io/install.sh | sh

    - name: Deploy to Fly
      run: |
        fly deploy -t ${{ secrets.FLY_TARGET }} -p .
      env:
        FLY_TARGET: ${{ secrets.FLY_TARGET }}
