name: Deploy to Fly

on:
  push:
    branches:
      - main

env:
  FLY_TARGET: ${{ secrets.FLY_TARGET }}

steps:
  - name: Install Fly CLI
    run: curl https://fly.io/install.sh | sh

  - name: Deploy to Fly
    run: fly deploy -t ${{ env.FLY_TARGET }} -p .

